version: '3.8'
services:
  web:
    container_name: webscrapper
    image: 856886856235.dkr.ecr.eu-west-3.amazonaws.com/robotdorm-server:latest
    env_file:
      - ./.env
    ports:
      - 80:8000
    links:
      - mongodb
    networks:
      - webapp-network
    depends_on:
      - mongodb
  mongodb:
    container_name: mongo
    image: mongo:latest
    volumes:
      - ~/db/mongo:/data/db
    restart: always
    command: [--auth]
    env_file:
      - ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
      - MONGO_INITDB_DATABASE_NAME=$DB_NAME
    ports:
      - 80:27017
    networks:
      - webapp-network  
networks:
  webapp-network:
    driver: bridge
