version: '3.4'

services:
  mongodb:
    container_name: mongodb
    image: mongo:5.0.2
    volumes:
      - ~/mongo:/data/db
    restart: unless-stopped
    env_file: 
      - ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
      - MONGO_INITDB_DATABASE_NAME=$MONGODB_DATABASE
    ports:
      - "27017:27017"
    networks:
      - webapp-network
  web:
    depends_on:
      - mongodb
    container_name: webscrapper_server
    image: webscrapper:v3
    build:
      context: ./server
      dockerfile: ./Dockerfile
    environment:
      - WAIT_HOSTS=mongodb:27017
    env_file:
      - ./server/.env
    networks:
      - webapp-network

    ports:
      - 8000:8000
networks:
  webapp-network:
    driver: bridge 